version: '3.0'

services:
  mongodb_container:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - "zdmpuda"
      
  mongo-express:
    image: mongo-express
    container_name: mongodbexpress
    hostname: mongodbexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
    networks:
      - "zdmpuda"
      
  xafserver:
    image: swmscon.azurecr.io/zdmpudacomponentblazorserver:latest
    container_name: xafserver
    hostname: xafserver
    restart: always
    ports:
      - 4000:80
    environment:
      SQL_PROVIDER: MSSqlServer
      SQL_SERVER: sqldata
      SQL_USER: sa
      SQL_PASSWORD: Pass@word
      SQL_CATALOG: zdmpUDAtest
    networks:
      - "zdmpuda"
      
  zdmpudabackend:
    image: swmscon.azurecr.io/zdmpudabackend:latest
    container_name: zdmpudabackend
    hostname: zdmpudabackend
    restart: always
    ports:
      - 5000:80
    networks:
      - "zdmpuda"
      
  zdmpudacomponentbackendwebapi:
    image: swmscon.azurecr.io/zdmpudacomponentbackendwebapi:latest
    container_name: zdmpudacomponentbackendwebapi
    hostname: zdmpudacomponentbackendwebapi
    restart: always
    ports:
      - 6000:80
    networks:
      - "zdmpuda"
      
  sqldata:
    container_name: sqldata
    hostname: sqldata
    restart: always
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
      - mssql_secrets:/var/opt/mssql/secrets
    environment:
      - MSSQL_PID=Express
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - "zdmpuda"

volumes:
  mongodb_data_container:
  mssql_data:
  mssql_log:
  mssql_secrets:
  
networks:
  zdmpuda:
    external: true
