apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c --replicas=1
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-container
  name: mongodb-container
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
      nodePort: 30004
  type: NodePort
  selector:
    io.kompose.service: mongodb-container
status:
  loadBalancer: {}
