{{- if .Values.defaultSettings.registrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultSettings.registrySecret }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "zdmp-uda.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "secret" . }}
{{- end }}
